<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".git" />
    <None Remove=".gitignore" />
    <None Remove="LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Control\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FormRx\FormRx.csproj" />
    <ProjectReference Include="..\PKHeXUtilLib\PKHeXUtilLib.csproj" />
  </ItemGroup>

</Project>
